on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2 
    - uses: nuget/setup-nuget@04b0c2b8d1b97922f67eca497d7cf0bf17b8ffe1 # pin@v1.0.5 
      with:
        nuget-version: 5.x
    - run: nuget restore
    - uses: microsoft/setup-msbuild@c26a08ba26249b81327e26f6ef381897b6a8754d # pin@v1 
    - name: build
      run: msbuild /p:Configuration=Release /p:"Platform=Any CPU"
      shell: cmd
